### ISSUE TITLE
control restart failes

### ISSUE THREAD

**Issue by DANA-Laboratory** [ivandavid77/julia-cartridge#1]
Following this instruction, I created an application with julia-cartridge using my free Open-Shift account, it works, but when I want to restart my app it fails **Failed to execute: 'control restart' for ...** also I can't push changes to origin due to a same failure.

**Comment by ivandbarron** [comment]
Ok,restart app look for .server.jl file, you can check this in: https://github.com/ivandavid77/julia-cartridge/blob/master/bin/control#L20 ,  if your project uses another file for serving, you must modify control script, it is located at ~/julia/bin/control inside your openshift project

**Comment by ivandbarron** [comment]
but if it is a fresh install maybe "start" does not execute on cartridge creation, so you must ssh to your project (using preferably red hat client) and type "gear start" in shell

**Comment by DANA-Laboratory** [comment]
Thanks for your helpful recommendations, and your quick response.
